name: CI (LaTeX)

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    name: build-LaTeX

    env:
      COQ_VERSION: "master"
      COQ_PACKAGE: "coq libcoq-core-ocaml-dev"
      PPA: "ppa:jgross-h/coq-master-daily"

    steps:
    - name: install deps
      run: |
        if [ ! -z "$PPA" ]; then sudo add-apt-repository "$PPA" -y; fi
        sudo apt-get -o Acquire::Retries=30 update -q
        sudo apt-get -o Acquire::Retries=30 install -y --allow-unauthenticated \
          ocaml-findlib $COQ_PACKAGE \
          texlive \
          texlive-latex-extra \
          texlive-bibtex-extra \
          texlive-science \
          texlive-luatex \
          texlive-lang-greek \
          lmodern \
          biber \
          gnuplot-nox \
          wget \
          curl \
          sed \
          grep \
          pdf2svg \
          python-is-python3 \
          python3-pygments
    - uses: actions/checkout@v4
    - run: make pdf
    - run: make doc
    - run: make copy-pdf
    - run: make copy-doc
    - name: Deploy pdfs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc-build
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
