name: CI (LaTeX)

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install deps
      run: |
        sudo apt-get -o Acquire::Retries=30 update -q
        sudo apt-get -o Acquire::Retries=30 install -y --allow-unauthenticated \
          coq \
          texlive \
          texlive-latex-extra \
          texlive-bibtex-extra \
          texlive-generic-extra \
          texlive-science \
          texlive-luatex \
          texlive-lang-greek \
          lmodern \
          biber \
          gnuplot-nox \
          wget \
          curl \
          sed \
          grep \
          pdf2svg \
          python \
          python-pygments
    - uses: actions/checkout@v2
    - run: make pdf
    - run: make doc
    - run: make copy-pdf
    - run: make copy-doc
    - name: Deploy pdfs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc-build
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
